INSERT INTO designations(designation_name) VALUES('PRINCIPAL SECRETARY');
INSERT INTO designations(designation_name) VALUES('SECRETARY');
INSERT INTO designations(designation_name) VALUES('ADDITIONAL SECRETARY');
INSERT INTO designations(designation_name) VALUES('CHIEF ENGINEER WEST ZONE PWD');
INSERT INTO designations(designation_name) VALUES('DIRECTOR OF LOCAL BODIES');
INSERT INTO designations(designation_name) VALUES('SUPERINTENDING ENGINEER');
INSERT INTO designations(designation_name) VALUES('SUPERINTENDING ENGINEER (CIVIL)');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER');
INSERT INTO designations(designation_name) VALUES('CHIEF ENGINEER PWD HEAD QTR');
INSERT INTO designations(designation_name) VALUES('CHIEF ENGINEER');
INSERT INTO designations(designation_name) VALUES('SPECIAL  SECRETARY');
INSERT INTO designations(designation_name) VALUES('SUPERINTENDING ENGINEER  ');
INSERT INTO designations(designation_name) VALUES('DIRECTOR & CHIEF ENGINEER');
INSERT INTO designations(designation_name) VALUES('ASSISTANT CHIEF ENGINEER (CIVIL)');
INSERT INTO designations(designation_name) VALUES('SPECIAL ENGINEER');
INSERT INTO designations(designation_name) VALUES('SUPERINTENDING ENGINEER (MECHANICAL)');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, SOUTHERN MECHANICAL DIVISION');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER SOUTH WESTERN MECH DIVISION');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, WESTERN MECHGANICAL DIVISION');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER(CIVIL)');
INSERT INTO designations(designation_name) VALUES('TECHNICAL ASSISTANT TO SUPERINTENDING ENGINEER');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER ');
INSERT INTO designations(designation_name) VALUES('SUPERINTENDENT, GOVERNOR''S ESTATE, W.B.');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER (CIVIL)');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, NORTHERN MECHANICAL DIVISION');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER (ELECTRICAL)');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER  (ELECYTICAL),PWD');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER(ELECT)');
INSERT INTO designations(designation_name) VALUES('EXCEUTIVE ENGINEER');
INSERT INTO designations(designation_name) VALUES('SUPERINTENDING ENGINEER (ELECTRICAL)');
INSERT INTO designations(designation_name) VALUES('SUPERINTENDING ARCHITECT');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER (ELECTRICAL)  ');
INSERT INTO designations(designation_name) VALUES('DIVISIONAL ACCOUNTANT');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER II');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER (ELECTRICAL),PWD');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, PWD(ELECTRICAL)');
INSERT INTO designations(designation_name) VALUES('EE KED');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER(ELECTRICAL)');
INSERT INTO designations(designation_name) VALUES('ADDITIONAL  CHIEF ENGINEER');
INSERT INTO designations(designation_name) VALUES('ADDITIONAL DIRECTOR');
INSERT INTO designations(designation_name) VALUES('CHIEF ENGINEER, M.E.DTE');
INSERT INTO designations(designation_name) VALUES('COMPUTER OPERETOR');
INSERT INTO designations(designation_name) VALUES('JUNIOR ENGINEER');
INSERT INTO designations(designation_name) VALUES('CHIEF ENGINEER (M/E) NZ');
INSERT INTO designations(designation_name) VALUES('SUPERINTENDING ENGINEER(CIVIL)');
INSERT INTO designations(designation_name) VALUES('CHIEF ENGINEER(M/E)SZ');
INSERT INTO designations(designation_name) VALUES('CHIEF ENGINEER(WZ)');
INSERT INTO designations(designation_name) VALUES('ASSISTANT ENGINEER(CIVIL)');
INSERT INTO designations(designation_name) VALUES('ADDITIONAL CHIEF ENGINEER');
INSERT INTO designations(designation_name) VALUES('CHIEF ENGINEER(HQ)');
INSERT INTO designations(designation_name) VALUES('CHIEF ENGINEER (WEST)');
INSERT INTO designations(designation_name) VALUES('ASSISTANT ENGINEER');
INSERT INTO designations(designation_name) VALUES('ASSISTANT ENGINEER (CIVIL)');
INSERT INTO designations(designation_name) VALUES('HEAD CLERK');
INSERT INTO designations(designation_name) VALUES('ASSISTANT ENGINEER ');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER-I');
INSERT INTO designations(designation_name) VALUES('JUNIOR ENGINEER(CIVIL)');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER .');
INSERT INTO designations(designation_name) VALUES('DEPUTY SUPERINTENDING ENGINEER');
INSERT INTO designations(designation_name) VALUES('CHAIRMAN');
INSERT INTO designations(designation_name) VALUES('F.O');
INSERT INTO designations(designation_name) VALUES('CHAIRPERSON');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER');
INSERT INTO designations(designation_name) VALUES('CHAIRMAN, BOARD OF COUNCILORS');
INSERT INTO designations(designation_name) VALUES('MAYOR');
INSERT INTO designations(designation_name) VALUES('FO');
INSERT INTO designations(designation_name) VALUES('CHAIRPERSON BOARD OF ADMINISTRATOR');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE OFFICER');
INSERT INTO designations(designation_name) VALUES('COMMISSIONER');
INSERT INTO designations(designation_name) VALUES('VICE CHAIRMAN');
INSERT INTO designations(designation_name) VALUES('SANJIT');
INSERT INTO designations(designation_name) VALUES('CHAIRMAN BOARD OF ADMINISTRATOR');
INSERT INTO designations(designation_name) VALUES('MANAGING DIRECTOR');
INSERT INTO designations(designation_name) VALUES('CHIEF EXECUTIVE OFFICER');
INSERT INTO designations(designation_name) VALUES('CHAIRPERSON OF THE BOARD OF ADMINISTRATOR');
INSERT INTO designations(designation_name) VALUES('MEMBER SECRETARY & EX-OFFICIO JOINT SECRETARY');
INSERT INTO designations(designation_name) VALUES('DEPUTY DIRECTOR');
INSERT INTO designations(designation_name) VALUES('ASSISTANT DIRECTOR(A&A)');
INSERT INTO designations(designation_name) VALUES('ADMINISTRATOR');
INSERT INTO designations(designation_name) VALUES('ASSISTANT ENGINEER, CIVIL');
INSERT INTO designations(designation_name) VALUES('CHAIRPERSON BOARD OF ADMINISTRATORS');
INSERT INTO designations(designation_name) VALUES('ASSISTANT ENGINEER (MECHANICAL)');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER(ELECTRICAL),PWD');
INSERT INTO designations(designation_name) VALUES('ASSISTANT ENGINEER (E/M)');
INSERT INTO designations(designation_name) VALUES('ESTATE MANAGER');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER CIVIL');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINNER');
INSERT INTO designations(designation_name) VALUES('CGM');
INSERT INTO designations(designation_name) VALUES('ADDITIONAL DISTRICT MAGISTRATE');
INSERT INTO designations(designation_name) VALUES('PROJECT DIRECTOR');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE OFFICER ');
INSERT INTO designations(designation_name) VALUES('ENGINEER IN CHIEF');
INSERT INTO designations(designation_name) VALUES('DIRECTOR SUDA');
INSERT INTO designations(designation_name) VALUES('CHAIRPERSON, BOARD OF ADMINISTRATORS');
INSERT INTO designations(designation_name) VALUES('ASSISTANT ENGINEER CIVIL');
INSERT INTO designations(designation_name) VALUES('CHIEF ENGINEER & DIRECTOR');
INSERT INTO designations(designation_name) VALUES('CHIEF EXECUTIVE OFFICER, HIT');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER-I(M/E)');
INSERT INTO designations(designation_name) VALUES('SUB DIVISION OFFICER ( SADAR)');
INSERT INTO designations(designation_name) VALUES('CHAIRPERSON, BOARD OF COUNCILLORS');
INSERT INTO designations(designation_name) VALUES('SDO & EXECUTIVE OFFICER');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE OFFICER & ADM BIRBHUM');
INSERT INTO designations(designation_name) VALUES('SUB DIVISIONAL OFFICER');
INSERT INTO designations(designation_name) VALUES('EO, FSDA & SDO, SERAMPORE');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER (MECHANICAL)');
INSERT INTO designations(designation_name) VALUES('Junior Engineer (Electrical)');
INSERT INTO designations(designation_name) VALUES('Assistant Electrician');
INSERT INTO designations(designation_name) VALUES('Chowkidar');
INSERT INTO designations(designation_name) VALUES('Section Officer');
INSERT INTO designations(designation_name) VALUES('Lower Division Clerk');
INSERT INTO designations(designation_name) VALUES('Head Assistant');
INSERT INTO designations(designation_name) VALUES('Office Peon');
INSERT INTO designations(designation_name) VALUES('Mali');
INSERT INTO designations(designation_name) VALUES('Workman');
INSERT INTO designations(designation_name) VALUES('Night Guard');
INSERT INTO designations(designation_name) VALUES('Road Majdoor');
INSERT INTO designations(designation_name) VALUES('Junior Engineer (Civil)');
INSERT INTO designations(designation_name) VALUES('Peon');
INSERT INTO designations(designation_name) VALUES('Workman (Cleaning)');
INSERT INTO designations(designation_name) VALUES('Work Assistant');
INSERT INTO designations(designation_name) VALUES('Upper Division Clerk');
INSERT INTO designations(designation_name) VALUES('Typist Grade I');
INSERT INTO designations(designation_name) VALUES('Chief Engineer (Works) Electrical');
INSERT INTO designations(designation_name) VALUES('Guard');
INSERT INTO designations(designation_name) VALUES('Junior Pump Operator');
INSERT INTO designations(designation_name) VALUES('Roller Driver');
INSERT INTO designations(designation_name) VALUES('Accountant');
INSERT INTO designations(designation_name) VALUES('Mechanic Grade I');
INSERT INTO designations(designation_name) VALUES('Sweeper');
INSERT INTO designations(designation_name) VALUES('Record Supplier');
INSERT INTO designations(designation_name) VALUES('Mechanic');
INSERT INTO designations(designation_name) VALUES('Karmabandhu');
INSERT INTO designations(designation_name) VALUES('Peon Grade I');
INSERT INTO designations(designation_name) VALUES('Draftsman');
INSERT INTO designations(designation_name) VALUES('Personal Assistant (Schedule-B English Stenographer) Grade - II');
INSERT INTO designations(designation_name) VALUES('Roller Cleaner');
INSERT INTO designations(designation_name) VALUES('Work Guard');
INSERT INTO designations(designation_name) VALUES('Assistant Engineer (Electrical)');
INSERT INTO designations(designation_name) VALUES('Duplicating Operator');
INSERT INTO designations(designation_name) VALUES('Senior Accounts Clerk');
INSERT INTO designations(designation_name) VALUES('Estimator');
INSERT INTO designations(designation_name) VALUES('Divisional Accounts Officer Gr I');
INSERT INTO designations(designation_name) VALUES('Administrative Officer');
INSERT INTO designations(designation_name) VALUES('Junior Engineer (Mechanical)');
INSERT INTO designations(designation_name) VALUES('Deputy Secretary');
INSERT INTO designations(designation_name) VALUES('Senior Divisional Accounts Officer');
INSERT INTO designations(designation_name) VALUES('Head Draftsman');
INSERT INTO designations(designation_name) VALUES('Assistant Cook');
INSERT INTO designations(designation_name) VALUES('Upper Division Assistant');
INSERT INTO designations(designation_name) VALUES('Orderly');
INSERT INTO designations(designation_name) VALUES('Surveyor');
INSERT INTO designations(designation_name) VALUES('Room Attendent');
INSERT INTO designations(designation_name) VALUES('Electrical Technician');
INSERT INTO designations(designation_name) VALUES('DUFTERY');
INSERT INTO designations(designation_name) VALUES('Farash');
INSERT INTO designations(designation_name) VALUES('Senior Workman');
INSERT INTO designations(designation_name) VALUES('Duftry');
INSERT INTO designations(designation_name) VALUES('Law Officer');
INSERT INTO designations(designation_name) VALUES('Personal Assistant (Schedule-B English Stenographer) Grade-I');
INSERT INTO designations(designation_name) VALUES('Darwan Cum Night Guard Grade-I');
INSERT INTO designations(designation_name) VALUES('Cash Sarkar');
INSERT INTO designations(designation_name) VALUES('Assistant Chief Engineer (Planning)');
INSERT INTO designations(designation_name) VALUES('Head Electrician');
INSERT INTO designations(designation_name) VALUES('Peon Basic Grade');
INSERT INTO designations(designation_name) VALUES('Executive Engineer (Monitoring)');
INSERT INTO designations(designation_name) VALUES('Jeep Cleaner');
INSERT INTO designations(designation_name) VALUES('Typist Grade-I');
INSERT INTO designations(designation_name) VALUES('JUNIOR ASSISTANT');
INSERT INTO designations(designation_name) VALUES('Chief Engineer (Mechanical/Electrical) Southern Zone');
INSERT INTO designations(designation_name) VALUES('Junior Operator (Lift)');
INSERT INTO designations(designation_name) VALUES('Plumbing Mistry');
INSERT INTO designations(designation_name) VALUES('Farash Grade I');
INSERT INTO designations(designation_name) VALUES('Assistant Financial Advisor');
INSERT INTO designations(designation_name) VALUES('Lower Division Assistant');
INSERT INTO designations(designation_name) VALUES('Junior Lift Operator');
INSERT INTO designations(designation_name) VALUES('Work peon');
INSERT INTO designations(designation_name) VALUES('Tracer');
INSERT INTO designations(designation_name) VALUES('Muharrir Grade-II');
INSERT INTO designations(designation_name) VALUES('Head Surveyor');
INSERT INTO designations(designation_name) VALUES('Mazdoor');
INSERT INTO designations(designation_name) VALUES('Executive Engineer & Technical Assistant to Superintending Engineer');
INSERT INTO designations(designation_name) VALUES('Supervisory Grade Typist');
INSERT INTO designations(designation_name) VALUES('Assistant Architect');
INSERT INTO designations(designation_name) VALUES('Driver');
INSERT INTO designations(designation_name) VALUES('Plumbing Helper');
INSERT INTO designations(designation_name) VALUES('HEALTH OFFICER');
INSERT INTO designations(designation_name) VALUES('Assistant Executive Officer');
INSERT INTO designations(designation_name) VALUES('Room Boy cum bearer');
INSERT INTO designations(designation_name) VALUES('Orderly Peon');
INSERT INTO designations(designation_name) VALUES('Collecting Sarkar');
INSERT INTO designations(designation_name) VALUES('Senior Special Secretary');
INSERT INTO designations(designation_name) VALUES('Special Commissioner in the rank of Special Secretary');
INSERT INTO designations(designation_name) VALUES('Electrician');
INSERT INTO designations(designation_name) VALUES('Office Peon Grade-I');
INSERT INTO designations(designation_name) VALUES('Junior Fitter(Lift)');
INSERT INTO designations(designation_name) VALUES('Chief Engineer (Planning& Water Quality management)');
INSERT INTO designations(designation_name) VALUES('Peon cum Record Supplier');
INSERT INTO designations(designation_name) VALUES('Architectural Assistant');
INSERT INTO designations(designation_name) VALUES('Head Estimator');
INSERT INTO designations(designation_name) VALUES('Sweeper  Grade I');
INSERT INTO designations(designation_name) VALUES('Litho Khalasi');
INSERT INTO designations(designation_name) VALUES('Gang Mazdoor');
INSERT INTO designations(designation_name) VALUES('Darwan');
INSERT INTO designations(designation_name) VALUES('Visti');
INSERT INTO designations(designation_name) VALUES('Jeep Driver');
INSERT INTO designations(designation_name) VALUES('Surveyor Grade -I');
INSERT INTO designations(designation_name) VALUES('Senior Electrician');
INSERT INTO designations(designation_name) VALUES('Store Chowkidar');
INSERT INTO designations(designation_name) VALUES('Officer on Special Duty');
INSERT INTO designations(designation_name) VALUES('Controller of Finance');
INSERT INTO designations(designation_name) VALUES('Map Arranger cum Record Supplier');
INSERT INTO designations(designation_name) VALUES('Karmabandhu Grade I');
INSERT INTO designations(designation_name) VALUES('Stock Mazdoor');
INSERT INTO designations(designation_name) VALUES('Chainman');
INSERT INTO designations(designation_name) VALUES('Orderly Grade- I');
INSERT INTO designations(designation_name) VALUES('Cash Sarkar Grade I');
INSERT INTO designations(designation_name) VALUES('Senior Deputy Secretary');
INSERT INTO designations(designation_name) VALUES('Clerk-Cum-Typist');
INSERT INTO designations(designation_name) VALUES('Special Revenue Officer II');
INSERT INTO designations(designation_name) VALUES('Sub- Assistant Engineer');
INSERT INTO designations(designation_name) VALUES('Jamadar');
INSERT INTO designations(designation_name) VALUES('Supervisory Level of Head Clerk');
INSERT INTO designations(designation_name) VALUES('Electrician Grade - I');
INSERT INTO designations(designation_name) VALUES('Tracer Grade-I');
INSERT INTO designations(designation_name) VALUES('Linesman Grade I');
INSERT INTO designations(designation_name) VALUES('Draftsman Grade I');
INSERT INTO designations(designation_name) VALUES('Workman Supernumerary');
INSERT INTO designations(designation_name) VALUES('Work Assistant Grade-I');
INSERT INTO designations(designation_name) VALUES('Table Boy cum Bearer');
INSERT INTO designations(designation_name) VALUES('Toll Chowkidar');
INSERT INTO designations(designation_name) VALUES('Senior Electrical Technician (Winding)');
INSERT INTO designations(designation_name) VALUES('Head Clerk cum Cashier');
INSERT INTO designations(designation_name) VALUES('STORE GUARD');
INSERT INTO designations(designation_name) VALUES('Deputy Financial Advisor');
INSERT INTO designations(designation_name) VALUES('Joint Director');
INSERT INTO designations(designation_name) VALUES('Assistant Secretary');
INSERT INTO designations(designation_name) VALUES('Copyist Basic Grade');
INSERT INTO designations(designation_name) VALUES('Assistant Machinist (Turner)');
INSERT INTO designations(designation_name) VALUES('Registrar');
INSERT INTO designations(designation_name) VALUES('Road Mate');
INSERT INTO designations(designation_name) VALUES('Senior Personal Assistant (Schedule-B English Stenographer)');
INSERT INTO designations(designation_name) VALUES('Divisional Accounts Officer Gr II');
INSERT INTO designations(designation_name) VALUES('Mechanic (Air Conditioning & Refrigeration)');
INSERT INTO designations(designation_name) VALUES('Junior Laboratory Assistant');
INSERT INTO designations(designation_name) VALUES('Carpenter');
INSERT INTO designations(designation_name) VALUES('Assistant Engineer Civil-I');
INSERT INTO designations(designation_name) VALUES('Chowkidar Grade I');
INSERT INTO designations(designation_name) VALUES('Chainman Grade I');
INSERT INTO designations(designation_name) VALUES('Blue Printer');
INSERT INTO designations(designation_name) VALUES('Group D Grade I');
INSERT INTO designations(designation_name) VALUES('Duplicating operator Grade-I');
INSERT INTO designations(designation_name) VALUES('Supervisor Typist');
INSERT INTO designations(designation_name) VALUES('Vehicle Cleaner');
INSERT INTO designations(designation_name) VALUES('Driver Basic Grade');
INSERT INTO designations(designation_name) VALUES('Table Boy');
INSERT INTO designations(designation_name) VALUES('Blue Printer Khalasi');
INSERT INTO designations(designation_name) VALUES('Muharrir Grade II');
INSERT INTO designations(designation_name) VALUES('Associate Town Planner');
INSERT INTO designations(designation_name) VALUES('T.A. to Suptd. Engineer');
INSERT INTO designations(designation_name) VALUES('Muharrir Grade-I');
INSERT INTO designations(designation_name) VALUES('Head Durwan Grade-I');
INSERT INTO designations(designation_name) VALUES('Godown Keeper');
INSERT INTO designations(designation_name) VALUES('Accounts Clerk');
INSERT INTO designations(designation_name) VALUES('Sub-Assistant Engineer (Mechanical)');
INSERT INTO designations(designation_name) VALUES('Junior Fitter');
INSERT INTO designations(designation_name) VALUES('Cleaner Grade-I');
INSERT INTO designations(designation_name) VALUES('Supervisory Incharge');
INSERT INTO designations(designation_name) VALUES('Executive Engineer (Planning)');
INSERT INTO designations(designation_name) VALUES('Barkandaz');
INSERT INTO designations(designation_name) VALUES('Cashier');
INSERT INTO designations(designation_name) VALUES('Liaison Officer');
INSERT INTO designations(designation_name) VALUES('Sub-Assistant Engineer (Drilling)');
INSERT INTO designations(designation_name) VALUES('Cane Mistry Grade-I');
INSERT INTO designations(designation_name) VALUES('Driver Grade I');
INSERT INTO designations(designation_name) VALUES('Junior Assistant Planner');
INSERT INTO designations(designation_name) VALUES('Assistant Operator (Cooling Plant)');
INSERT INTO designations(designation_name) VALUES('Vehicle Driver');
INSERT INTO designations(designation_name) VALUES('Assistant Pay Clerk');
INSERT INTO designations(designation_name) VALUES('Telephone Operator');
INSERT INTO designations(designation_name) VALUES('senior supervisory grade typist');
INSERT INTO designations(designation_name) VALUES('Chowkidar cum Night Guard');
INSERT INTO designations(designation_name) VALUES('Assistant Town Planner');
INSERT INTO designations(designation_name) VALUES('Muharrir Grade I');
INSERT INTO designations(designation_name) VALUES('Lines Man');
INSERT INTO designations(designation_name) VALUES('Joint Director (Finance)');
INSERT INTO designations(designation_name) VALUES('Data Entry Operator');
INSERT INTO designations(designation_name) VALUES('Operator (Cooling Plant)');
INSERT INTO designations(designation_name) VALUES('Investigator');
INSERT INTO designations(designation_name) VALUES('Assistant Investigator Grade I');
INSERT INTO designations(designation_name) VALUES('Asstt. Chief Engineer');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER I');
INSERT INTO designations(designation_name) VALUES('Officer on Special Duty To Minister-in-Charge');
INSERT INTO designations(designation_name) VALUES('Deputy Director ((Accounts Audit & Verification)');
INSERT INTO designations(designation_name) VALUES('Truck Cleaner');
INSERT INTO designations(designation_name) VALUES('Duplicating Machine Operator (Grade-I)');
INSERT INTO designations(designation_name) VALUES('Mathor');
INSERT INTO designations(designation_name) VALUES('CHIEF ENGINEER (HQ)');
INSERT INTO designations(designation_name) VALUES('General Manager (Accounts)');
INSERT INTO designations(designation_name) VALUES('Assistant Chief Engineer (Electrical)');
INSERT INTO designations(designation_name) VALUES('Senior Electrical Technician (Testing)');
INSERT INTO designations(designation_name) VALUES('Deputy Director(Audit & Accounts)');
INSERT INTO designations(designation_name) VALUES('Deputy Director Finance');
INSERT INTO designations(designation_name) VALUES('Room Attendant cum bearer');
INSERT INTO designations(designation_name) VALUES('Inspector');
INSERT INTO designations(designation_name) VALUES('Cleaner');
INSERT INTO designations(designation_name) VALUES('Work Chowkidar');
INSERT INTO designations(designation_name) VALUES('Assistant Chief Engineer (Monitoring)');
INSERT INTO designations(designation_name) VALUES('Research Officer');
INSERT INTO designations(designation_name) VALUES('ASSISTANT CHIEF ENGINEER (PERSONNEL)');
INSERT INTO designations(designation_name) VALUES('Roller Guard');
INSERT INTO designations(designation_name) VALUES('Miscellenious Clerk');
INSERT INTO designations(designation_name) VALUES('Engineer in-Chief');
INSERT INTO designations(designation_name) VALUES('HEAD DRAUGHTSMAN');
INSERT INTO designations(designation_name) VALUES('Duplicating Machine Operator');
INSERT INTO designations(designation_name) VALUES('Helper');
INSERT INTO designations(designation_name) VALUES('Accounts Officer and Ex-Officio Assistant Secretary');
INSERT INTO designations(designation_name) VALUES('Personal Assistant (Schedule-B English Stenographer) Basic Grade');
INSERT INTO designations(designation_name) VALUES('Duplicator Operator');
INSERT INTO designations(designation_name) VALUES('Sweeper cum Mazdoor');
INSERT INTO designations(designation_name) VALUES('Clerk cum Typist Grade I');
INSERT INTO designations(designation_name) VALUES('Record Supplier Grade-I');
INSERT INTO designations(designation_name) VALUES('Architectectural Assistant');
INSERT INTO designations(designation_name) VALUES('Store Keeper');
INSERT INTO designations(designation_name) VALUES('Accounts Officer');
INSERT INTO designations(designation_name) VALUES('Joint Secretary');
INSERT INTO designations(designation_name) VALUES('Technical Secretary');
INSERT INTO designations(designation_name) VALUES('I.B.Chowkidar');
INSERT INTO designations(designation_name) VALUES('Karmasathi Grade I');
INSERT INTO designations(designation_name) VALUES('DRAUGHTSMAN');
INSERT INTO designations(designation_name) VALUES('Law Assistant');
INSERT INTO designations(designation_name) VALUES('Head Clerk cum Accountant');
INSERT INTO designations(designation_name) VALUES('Darwan Grade-I');
INSERT INTO designations(designation_name) VALUES('Officer-on-Special Duty');
INSERT INTO designations(designation_name) VALUES('Architect');
INSERT INTO designations(designation_name) VALUES('Cook');
INSERT INTO designations(designation_name) VALUES('Assistant Fitter');
INSERT INTO designations(designation_name) VALUES('Head Machinist (Turner)');
INSERT INTO designations(designation_name) VALUES('Karma bandhu');
INSERT INTO designations(designation_name) VALUES('Chief Auditor');
INSERT INTO designations(designation_name) VALUES('Plumbing Mazdoor');
INSERT INTO designations(designation_name) VALUES('Khalasi');
INSERT INTO designations(designation_name) VALUES('Superintendent Governor''s Estate');
INSERT INTO designations(designation_name) VALUES('Private Secretary to MIC');
INSERT INTO designations(designation_name) VALUES('Group D');
INSERT INTO designations(designation_name) VALUES('Municipal Commissioner');
INSERT INTO designations(designation_name) VALUES('Principal Secretary');
INSERT INTO designations(designation_name) VALUES('Special Secretary and Financial Advisor');
INSERT INTO designations(designation_name) VALUES('Assistant Director (Audit & Accounts)');
INSERT INTO designations(designation_name) VALUES('Assistant Caretaker');
INSERT INTO designations(designation_name) VALUES('Senior Worksman');
INSERT INTO designations(designation_name) VALUES('Automatic Vote Recording Equipment Operator');
INSERT INTO designations(designation_name) VALUES('Assistant Chief Engineer (Mechanical/Electrical)');
INSERT INTO designations(designation_name) VALUES('Mali Grade I');
INSERT INTO designations(designation_name) VALUES('Treasury Guard');
INSERT INTO designations(designation_name) VALUES('Sub-Assistant Engineer (Civil)');
INSERT INTO designations(designation_name) VALUES('Workman Labourer');
INSERT INTO designations(designation_name) VALUES('Chief Engineer Electrical (Planning)');
INSERT INTO designations(designation_name) VALUES('Senior Law Officer & Ex-Officio Assistant Secretary (Law)');
INSERT INTO designations(designation_name) VALUES('Chief Town Planner');
INSERT INTO designations(designation_name) VALUES('Office Chowkidar');
INSERT INTO designations(designation_name) VALUES('Special Law Officer & Ex Officio  Deputy Secretary');
INSERT INTO designations(designation_name) VALUES('Assistant Electrician Grade I');
INSERT INTO designations(designation_name) VALUES('Plumber');
INSERT INTO designations(designation_name) VALUES('Member');
INSERT INTO designations(designation_name) VALUES('Assistant Estate Manager');
INSERT INTO designations(designation_name) VALUES('Karmasathi (Jamadar)');
INSERT INTO designations(designation_name) VALUES('Assistant Investigator');
INSERT INTO designations(designation_name) VALUES('Special Secretary');
INSERT INTO designations(designation_name) VALUES('Senior Law Officer');
INSERT INTO designations(designation_name) VALUES('Deputy Municpal Commssioner');
INSERT INTO designations(designation_name) VALUES('Land Manager');
INSERT INTO designations(designation_name) VALUES('Technical Assistant');
INSERT INTO designations(designation_name) VALUES('Financial Advisor');
INSERT INTO designations(designation_name) VALUES('Messenger Peon');
INSERT INTO designations(designation_name) VALUES('Accountant cum Cashier');
INSERT INTO designations(designation_name) VALUES('Joint Municpal Commissioner');
INSERT INTO designations(designation_name) VALUES('Urban Land Ceiling Officer');
INSERT INTO designations(designation_name) VALUES('Upholsterer');
INSERT INTO designations(designation_name) VALUES('Special Law Officer & Ex-Officio Deputy Secretary (Law)');
INSERT INTO designations(designation_name) VALUES('Deputy Secretary (Technical)');
INSERT INTO designations(designation_name) VALUES('Typist');
INSERT INTO designations(designation_name) VALUES('Chief Engineer (Civil)');
INSERT INTO designations(designation_name) VALUES('Assistant Toll Collector');
INSERT INTO designations(designation_name) VALUES('Sanitary Supervisor');
INSERT INTO designations(designation_name) VALUES('Senior Fitter');
INSERT INTO designations(designation_name) VALUES('Plumbing Khalasi');
INSERT INTO designations(designation_name) VALUES('Visty Grade I');
INSERT INTO designations(designation_name) VALUES('Head Assistant cum Accountant');
INSERT INTO designations(designation_name) VALUES('Information Assistant');
INSERT INTO designations(designation_name) VALUES('Chief Engineer (North)');
INSERT INTO designations(designation_name) VALUES('  TA TO SE, P & M CIRCLE, PWD');
INSERT INTO designations(designation_name) VALUES('3RD GRADE CLERK');
INSERT INTO designations(designation_name) VALUES('3RD. GRADE CLERK');
INSERT INTO designations(designation_name) VALUES('A. E., HOWRAH MECHANICAL SUBDIVISION');
INSERT INTO designations(designation_name) VALUES('A. E.. , R. W. S. PURULIA SUB-DIVISION');
INSERT INTO designations(designation_name) VALUES('A.E.,R.W.S NADIA SUB-DIVISION,PHE DTE');
INSERT INTO designations(designation_name) VALUES('A.O. & EX-OFFICIO A.S.');
INSERT INTO designations(designation_name) VALUES('ADDITIONAL  DIRECTOR, I.L.G.U.S.');
INSERT INTO designations(designation_name) VALUES('ADDL. SECRETARY');
INSERT INTO designations(designation_name) VALUES('ADM GEN');
INSERT INTO designations(designation_name) VALUES('AE (EL)');
INSERT INTO designations(designation_name) VALUES('AE, BURDWAN SI SUB-DIV, PHE');
INSERT INTO designations(designation_name) VALUES('AO');
INSERT INTO designations(designation_name) VALUES('AO AND EX OFFI CIO JT SECY');
INSERT INTO designations(designation_name) VALUES('AOICDS');
INSERT INTO designations(designation_name) VALUES('AP&AO');
INSERT INTO designations(designation_name) VALUES('ASISTANT ENGINEER, ALIPURDUAR RWS SUB DIVISION.PHE');
INSERT INTO designations(designation_name) VALUES('ASSISTANT CHIEF ENGINEER');
INSERT INTO designations(designation_name) VALUES('ASSISTANT CHIEF ENGINEER (P)');
INSERT INTO designations(designation_name) VALUES('ASSISTANT DIRECTOR');
INSERT INTO designations(designation_name) VALUES('ASSISTANT ENGINEER (CIVIL), PWS RAIGANJ SUB-DIVISION, P.H.E. DTE.');
INSERT INTO designations(designation_name) VALUES('ASSISTANT ENGINEER SURVEY SUB-DIV, BURDWAN.');
INSERT INTO designations(designation_name) VALUES('ASSISTANT ENGINEER(CIVIL)-I');
INSERT INTO designations(designation_name) VALUES('ASSISTANT ENGINEER, CALCUTTA S. I. SUB DIVISION');
INSERT INTO designations(designation_name) VALUES('ASSISTANT ENGINEER, RWS MIDNAPUR, PHE DTE');
INSERT INTO designations(designation_name) VALUES('ASSISTANT ENGINEER, SURVEY DIVISION-I, PHE DTE');
INSERT INTO designations(designation_name) VALUES('ASSISTANT ENGINEER,PIU SL WORK');
INSERT INTO designations(designation_name) VALUES('ASSISTANT ENGINEER-I');
INSERT INTO designations(designation_name) VALUES('ASSISTAT ENGINEER (CIVIL) I, SOUTH ZONE');
INSERT INTO designations(designation_name) VALUES('ASST DIRECTOR (A/C)');
INSERT INTO designations(designation_name) VALUES('ASST. ENG.(CIVIL)');
INSERT INTO designations(designation_name) VALUES('ASSTT. ENGINEER RWS BARASAT SUB-DIV');
INSERT INTO designations(designation_name) VALUES('ASSTT. ENGINEER, SILIGURI MECH. SUB-DIV., PHE');
INSERT INTO designations(designation_name) VALUES('ATO');
INSERT INTO designations(designation_name) VALUES('BDO APD2');
INSERT INTO designations(designation_name) VALUES('CE');
INSERT INTO designations(designation_name) VALUES('CHIEF ENGINEER, HQ PHE DTE');
INSERT INTO designations(designation_name) VALUES('CHIEF ENGINEER, MED');
INSERT INTO designations(designation_name) VALUES('COF HMC');
INSERT INTO designations(designation_name) VALUES('COMMISSIONER ');
INSERT INTO designations(designation_name) VALUES('COMPUTER OPERATOR');
INSERT INTO designations(designation_name) VALUES('D A ');
INSERT INTO designations(designation_name) VALUES('DAO');
INSERT INTO designations(designation_name) VALUES('DAO GR II');
INSERT INTO designations(designation_name) VALUES('DAO GR-I');
INSERT INTO designations(designation_name) VALUES('DAO GR. I');
INSERT INTO designations(designation_name) VALUES('DAO-I');
INSERT INTO designations(designation_name) VALUES('DEO');
INSERT INTO designations(designation_name) VALUES('DEPUTY DIRECTOR(A&A)');
INSERT INTO designations(designation_name) VALUES('DEPUTY S. E., MECHANICAL CIRCLE II');
INSERT INTO designations(designation_name) VALUES('DEPUTY SUPDT ENGINEER');
INSERT INTO designations(designation_name) VALUES('DEPUTY SUPDT. ENGINEER, EASTERN CIRCLE');
INSERT INTO designations(designation_name) VALUES('DEPUTY SUPERINTENDENT ENGINEER, W C, PHE DTE');
INSERT INTO designations(designation_name) VALUES('DEPUTY SUPERINTENDING ENGINEER, BANKURA W/S CIRCLE');
INSERT INTO designations(designation_name) VALUES('DISTRICT MAGISTRATE & DISTRICT COLLECTOR');
INSERT INTO designations(designation_name) VALUES('DISTRICT MAGISTRATE AND DISTRICT COLLECTOR');
INSERT INTO designations(designation_name) VALUES('DISTRICT PLANNING OFFICER');
INSERT INTO designations(designation_name) VALUES('DISTRICT YOUTH OFFICER');
INSERT INTO designations(designation_name) VALUES('DIVISIONAL  ACCOUNTANT');
INSERT INTO designations(designation_name) VALUES('DIVISIONAL ACCOUNTANT (P)');
INSERT INTO designations(designation_name) VALUES('DIVISIONAL ACCOUNTS OFFICER');
INSERT INTO designations(designation_name) VALUES('DIVISIONAL ACCOUNTS OFFICER  GR-II');
INSERT INTO designations(designation_name) VALUES('DIVISIONAL ACCOUNTS OFFICER GR-I');
INSERT INTO designations(designation_name) VALUES('DIVISIONAL ACCOUNTS OFFICER GR.II');
INSERT INTO designations(designation_name) VALUES('DIVISIONAL ACCOUNTS OFFICER, GR-I');
INSERT INTO designations(designation_name) VALUES('DIVISIONAL ACCOUNTS OFFICER, GR.-I');
INSERT INTO designations(designation_name) VALUES('DIVISIONAL ACCOUNTS OFFICER, GRADE-I');
INSERT INTO designations(designation_name) VALUES('DIVSIONAL ACCOUNTANT');
INSERT INTO designations(designation_name) VALUES('DM & DC');
INSERT INTO designations(designation_name) VALUES('DMDC');
INSERT INTO designations(designation_name) VALUES('DSE');
INSERT INTO designations(designation_name) VALUES('DSE, MECHANICAL CIRCLE-I');
INSERT INTO designations(designation_name) VALUES('DY SUPDT ENG MECH CIRCLE III');
INSERT INTO designations(designation_name) VALUES('DY. S.E., SOUTH 24 PGS W/S CIRCLE');
INSERT INTO designations(designation_name) VALUES('DY. SUPDT. ENGINEER, P.H ENGINEERING DTE.');
INSERT INTO designations(designation_name) VALUES('E E PUR HIGHWAY DIV');
INSERT INTO designations(designation_name) VALUES('E E SURVEY DIVISION');
INSERT INTO designations(designation_name) VALUES('E. E., PURULIA DIVISION, P. W. D.');
INSERT INTO designations(designation_name) VALUES('E.E .MALDA MECHANICAL DIVISION');
INSERT INTO designations(designation_name) VALUES('E.E, CENTRAL MECHANICAL DIV, BURDWAN');
INSERT INTO designations(designation_name) VALUES('E.E, SOCIAL SECTOR, PWD, MALDA');
INSERT INTO designations(designation_name) VALUES('E.E. MALDA HIGHWAY DIVISION');
INSERT INTO designations(designation_name) VALUES('E.E.(ELE), SW IT DIV. PW DTE.');
INSERT INTO designations(designation_name) VALUES('E.E., PAS. MED. ELECTRICAL DIV., P.W. DTE.');
INSERT INTO designations(designation_name) VALUES('E.E., PAS. MED. H.W. DIV.-II, P.W.(ROAD) DTE.');
INSERT INTO designations(designation_name) VALUES('E.E., SWP AND DESIGN DIVISION, P.W. DTE.');
INSERT INTO designations(designation_name) VALUES('EE');
INSERT INTO designations(designation_name) VALUES('EE & TA TO SUPERINTENDING ENGINEER');
INSERT INTO designations(designation_name) VALUES('EE (PWD) KOLKATA CENTRALHEALTH DIVISION ');
INSERT INTO designations(designation_name) VALUES('EE ELECTRICAL BURDWAN DIVISION');
INSERT INTO designations(designation_name) VALUES('EE PWD BIRBHUM DIVISION');
INSERT INTO designations(designation_name) VALUES('EE, BURDWAN SOUTH HIGHWAY DIVISION');
INSERT INTO designations(designation_name) VALUES('EE, ELECTRICAL DIVISION, PHE');
INSERT INTO designations(designation_name) VALUES('EE, KOLKATA CENTRAL DIV');
INSERT INTO designations(designation_name) VALUES('EE, KOLKATA CENTRAL ELEC DIV');
INSERT INTO designations(designation_name) VALUES('EE, KOLKATA ELECTRICAL DIV');
INSERT INTO designations(designation_name) VALUES('EE, KOLKATA NORTH DIV');
INSERT INTO designations(designation_name) VALUES('EE, NB DIV., SOCIAL SECTOR, PWD');
INSERT INTO designations(designation_name) VALUES('EE, NH PLANNING & DESIGN DIVISION -IV');
INSERT INTO designations(designation_name) VALUES('EE, NKHED');
INSERT INTO designations(designation_name) VALUES('EE, P & D DIVN - II');
INSERT INTO designations(designation_name) VALUES('EE, PHE, DAKSHIN DINAJPUR');
INSERT INTO designations(designation_name) VALUES('EE, PWD(CIVIL), SOUTH 24 PGS DIVISION');
INSERT INTO designations(designation_name) VALUES('EE, PWDSS, BANKURA DIV.');
INSERT INTO designations(designation_name) VALUES('EE, PWE, DAKSHIN DINAJPUR');
INSERT INTO designations(designation_name) VALUES('EE, RESOURSE DIVISION');
INSERT INTO designations(designation_name) VALUES('EE, S. 24 PGS DIVN., SOCIAL SECTOR');
INSERT INTO designations(designation_name) VALUES('EE,SOCIAL SECTOR');
INSERT INTO designations(designation_name) VALUES('EX. ENGINEER');
INSERT INTO designations(designation_name) VALUES('EX. ENGINEER, PWD NORTH 24-PGS ELEC DIVISION');
INSERT INTO designations(designation_name) VALUES('EX. ENGR.NORTHERN MECHANICAL DIVISION P.W. ROADS D');
INSERT INTO designations(designation_name) VALUES('EX.ENGINEER, PLANNING & DESIGN DVN. P.H.E');
INSERT INTO designations(designation_name) VALUES('EXE ENGINEER, MED');
INSERT INTO designations(designation_name) VALUES('EXE ENGR, DESIGN DN 1, PWD DTE');
INSERT INTO designations(designation_name) VALUES('EXE. ENGINEER BANKURA DIVN M.E. DIRECTORATE');
INSERT INTO designations(designation_name) VALUES('EXE. ENGINEER(ELEC.), N. BENGAL I.T. DIV.');
INSERT INTO designations(designation_name) VALUES('EXE. ENGINEER, MED');
INSERT INTO designations(designation_name) VALUES('EXE. ENGINEER, NH DIV -III, DGP');
INSERT INTO designations(designation_name) VALUES('EXE. ENGINEER, PLANNING & DESIGN DIVISION-V, PW DT');
INSERT INTO designations(designation_name) VALUES('EXE. ENGINEER, PWD (ROADS)');
INSERT INTO designations(designation_name) VALUES('EXE. ENGINEER, PWD ELEC CONSTRUCTION DIVISION.');
INSERT INTO designations(designation_name) VALUES('EXE. ENGINEER, PWD ELECTRICAL');
INSERT INTO designations(designation_name) VALUES('EXE. ENGINEER, PWD S24PGS ELECTRICAL DIVISION');
INSERT INTO designations(designation_name) VALUES('EXE. ENGINEER, SOUTRH 24-PGS.,W/S DIV.- I PHE DTE.');
INSERT INTO designations(designation_name) VALUES('EXE. ENGINEER,SOUTHERN HIGHWAY PLN. DIV -II,PWD');
INSERT INTO designations(designation_name) VALUES('EXE.ENGINEER, ALIPORE DIVISION (PWD)');
INSERT INTO designations(designation_name) VALUES('EXECUTIE EVNGINEER SOCIAL SECTOR BDWN DIV');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENG.,SOUTHERN HIGHWAY DIV. PW(ROADS)');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER & T A TO S E ASSISTANT TO SUPERINTENDING ENGINEER');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER & T.A TO S.E');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER & TA TO SUPERINTENDING ENGINEER');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER (CIVIL) - II');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER (CIVIL),MED, WEST CIRCLE');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER (CIVIL),PIU, BANKURA');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER (CIVIL)-I, PMU, PURULIA');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER BHD-I');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER HOWRAH ELECTRICAL DIV');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER MED');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER PHE MECHANICAL');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER PWD ELECTRICAL');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER PWD SOCIAL SECTOR');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER SOUTH CIRCLE M.E DTE KHARAGPUR');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, (M/E)');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, BANKURA DIVN. P.H.E.DTE.');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, DESIGN DIVISION III');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, HIGHWAY DIVISION APD');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, IT DIVISION');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, N.H. DIVN-X, PWD, ALIPURDUAR');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, NORTHAN MECHANICAL DIVI-II');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, PHE, MECHANICAL');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, PHE.DTE, ALIPURDUAR DIVISION');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, PURULIA DIVISION M.E.DTE.');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, PURULIA DIVISION, ');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, PWD, BISHNUPUR DIVISION');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, PWD, TAMLUK DIV');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, ROADS');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, SOCIAL SECTOR, NORTH 24 PGS P.W.D.');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER, WEST KOL ELECTRICAL DIVISION');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER,ME DTE.BURDWAN DIV.');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER,N..H.DIVISION-IV,P.W.(ROADS)DTE');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER,PHE,DTE.');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER,PHE,NADIA DIV');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER,PURULIA HIGHWAY DIVISION -II');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER,PWD CIVIL');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER,PWD(ROADS),BANKURA');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGINEER-II');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGNEER &TA  TO SE');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE ENGR.');
INSERT INTO designations(designation_name) VALUES('EXECUTIVE OFFICER , BURDWAN-I PS');
INSERT INTO designations(designation_name) VALUES('EXECUTIVEENGINEER,PURULIA,DIVISION,PHE,DTE');
INSERT INTO designations(designation_name) VALUES('F O BHADRESWAR MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('F O, JHARGRAM MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('F. O. TARAKESWAR MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('F.O SILIGURI MUNICIPAL CORPORATION');
INSERT INTO designations(designation_name) VALUES('F.O. ASHOKENAGAR-KALYANGARG MUNICIAPLITY');
INSERT INTO designations(designation_name) VALUES('F.O. SANTIPUR MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FA');
INSERT INTO designations(designation_name) VALUES('FAEASH');
INSERT INTO designations(designation_name) VALUES('FC & CAO');
INSERT INTO designations(designation_name) VALUES('FINANCE  OFFICER');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER ');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER APD MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER DOMKAL MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER KATWA MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER KHARAGPUR MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER TAMLUK');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, BADURIA MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, BALLY MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, BASIRHAT MUNICIPALITY.');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, BELDANAGA MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, BELDANGA MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, BISHNUPUR MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, BUDGE BUDGE MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, E. B MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, FALAKATA MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, HABRA MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, HALDIBARI MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, JHALDA MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, KRISHNANAGAR MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, MEKHLIGANJ MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, OLD MALDA MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, PURULIA MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, RAGHUNATHPUR MUN.');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, RAIGANJ MUNICIPALITY, RAIGANJ, UD');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, SONAMUKHI MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER, TAKI MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FINANCE OFFICER,KALNA MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FO BURDWAN MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FO CHAMPDANY MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FO MADHYAMGRAM MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FO TAHERPUR MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('FO, ULUBERIA MUNICIPALITY');
INSERT INTO designations(designation_name) VALUES('GROUD D');
INSERT INTO designations(designation_name) VALUES('H.A.');
INSERT INTO designations(designation_name) VALUES('HA');
INSERT INTO designations(designation_name) VALUES('HC');
INSERT INTO designations(designation_name) VALUES('HEAD ASSISANT');
INSERT INTO designations(designation_name) VALUES('HEAD CERK');
INSERT INTO designations(designation_name) VALUES('HEAD CLERCK');
INSERT INTO designations(designation_name) VALUES('HEAD CLERK ');
INSERT INTO designations(designation_name) VALUES('HEADCLERK');
INSERT INTO designations(designation_name) VALUES('HRMS OPERATOR');
INSERT INTO designations(designation_name) VALUES('INFORMATION ASSITANT');
INSERT INTO designations(designation_name) VALUES('JOINT SECRETARY (NURSING)');
INSERT INTO designations(designation_name) VALUES('JR. ENGINEER');
INSERT INTO designations(designation_name) VALUES('JT. SECRETARY');
INSERT INTO designations(designation_name) VALUES('JUNIOR ENGINEER( ELECTRICAL)');
INSERT INTO designations(designation_name) VALUES('L D CLERK');
INSERT INTO designations(designation_name) VALUES('L.D.C.');
INSERT INTO designations(designation_name) VALUES('L.D.CLERK');
INSERT INTO designations(designation_name) VALUES('LDA');
INSERT INTO designations(designation_name) VALUES('LDA/LDC');
INSERT INTO designations(designation_name) VALUES('LDC');
INSERT INTO designations(designation_name) VALUES('LOWER DIVISION ASSISTANT ');
